site_name: TOSCA Hands-On (INFN-2019)
theme:
  name: material
  logo:
    icon: cloud_circle
  palette:
    primary: 'indigo'
    accent: 'Red'
nav:
- Home: 'README.md'
- TOSCA Orchestration:
  - Overview: orchestrator/overview.md
  - Enviroment setup: 
     - Configure oidc-agent: orchestrator/oidc_agent.md
     - Configure orchent: orchestrator/orchent.md
  - Run your first deployment:
    - Hello world TOSCA template: orchestrator/tosca_blocks.md
    - Example - Elasticsearch template: orchestrator/elasticsearch_example.md 
  - Appendix:
    - TOSCA Usage Guide: orchestrator/tosca_usage_guide.md
repo_url: 'https://github.com/maricaantonacci/TOSCA-Hands-on'
markdown_extensions: 
 - codehilite:
    linenums: true
 - admonition:
 - pymdownx.superfences:

